# Scipy basic tutorial

- SciPy is a scientific ibrary for mathematics, science and engineering. 

- The SciPy library depends on NumPy, which provides convenient and fast N-dimensional array manipulation. 

### Scipy subpackages

https://docs.scipy.org/doc/scipy/reference/index.html

### Optimization

In [2]:
# Example: finding roots
import numpy as np
from scipy.optimize import brentq

x = brentq(np.sin,2,4) 
print (x, x-np.pi)

3.141592653589793 0.0


### Integration

In [3]:
# Example: integration
# import numpy as np
from scipy.integrate import simps, quad

# integrate from array using simpson
x = np.linspace(0, np.pi/2, 10000)
y = np.sin(x)
print( "sin(x) integral: ", simps(y,x) )

# integrate a function using gaussia quadrature
print( "exp(-x) integral: ", quad(lambda x: np.exp(-x), 0, np.inf) )

sin(x) integral:  0.9999999999998385
exp(-x) integral:  (1.0000000000000002, 5.842606703608969e-11)


### Statistics

In [4]:
# Example: geometric and harmonic means
# import numpy as np
from scipy import stats

range20 = np.arange(1,20)

print( "gmean: ", stats.gmean(range20) )
print( "hmean: ", stats.hmean(range20) )

gmean:  7.928946844865149
hmean:  5.355522624593338


### Linear Algebra

- scipy.linalg contains all the functions in numpy.linalg. plus some other more advanced ones not contained in numpy.linalg.

- scipy.linalg is compiled with BLAS/LAPACK support. 

- The scipy version might be faster depending on how numpy was installed.

In [7]:
# Example: find the inverse
# import numpy as np
from scipy import linalg

A = np.array([[1,3,5],[2,5,1],[2,3,8]])
B = linalg.inv(A)
C = A.dot(B)

print( "inverse:\n\n", C, end="\n\n" )
print( "determinant:\n\n", linalg.det(C) )

inverse:

 [[ 1.00000000e+00 -1.11022302e-16  4.85722573e-17]
 [ 3.05311332e-16  1.00000000e+00  7.63278329e-17]
 [ 2.22044605e-16 -1.11022302e-16  1.00000000e+00]]

determinant:

 0.9999999999999999


In [6]:
# Example solve matrix eq A X = B
A = np.array([ [-13,2,4], [2,-11,6], [4,6,-15] ])
B = np.array([5,-10,5])
print (linalg.solve(A,B))

[-0.28624535  0.81040892 -0.08550186]
