# IO operations

__Open modes__

Sintaxis

```Python
f = open(file, mode)

# file operations
# ...

f.close()
```

Modes
* 'r': Read mode allows you to read the fille. You can't change it, only read it.

* 'w': Write mode will create the file if it does not exist. If the file does exist,
opening it in 'w' mode will re-write it, destroying the current contents.

* 'a': Append mode allows you to write onto the end of a previously-existing
file without destroying what was there already.


__Reading methods__

* read the file contents into a single string

```Python
string = FileHandle.read( ) 
```

* read the current line of the file into a string and advance the cursor to next line

```Python
line = FileHandle.readline( )
```

* read the file contents into a list of strings, one string for each line.

```Python
lines = FileHandle.readlines( )
```

### read and write

In [23]:
import numpy as np

In [24]:
sum = np.pi + np.e

fileH = open("./data/pi-e.txt", 'w')

fileH.write("pi = %6.4f \t e=%6.4f \n" % (np.pi, np.e))
fileH.write("pi + e = %6.4f \n" % sum)

fileH.close( )

In [25]:
fileH = open("./data/pi-e.txt", 'r')

string = fileH.read()
print(string)

fileH.close( )

pi = 3.1416 	 e=2.7183 
pi + e = 5.8599 



### Read a numerical table

##### Read all file as a string

In [41]:
"12 13 14 \n 15 16 17".split()

['12', '13', '14', '15', '16', '17']

In [26]:
# Example: read a three-column numerical data
import numpy as np
fileH = open("./data/data-3-col.dat", 'r')

# all line a string
str1 = fileH.read()  

# split at each: space, \n, \t
str2 = str1.split() 

numbers1 = np.array([float(str_num) for str_num in str2])
numbers2 = np.reshape(numbers1, (3, numbers1.size//3))
numbers3 = np.reshape(numbers1, (numbers1.size//3, 3))

print(numbers2)
print(numbers3)

fileH.close( )

[[-5.          0.77107376  2.60662643 ... -1.39100345 -1.67
  -0.13831508]
 [-1.38967683 -1.66       -0.12416305 ... -0.06391766  0.71463459
   1.67      ]
 [-0.07091871  0.7125332   1.68       ...  5.          0.10435349
  -0.35276853]]
[[-5.          0.77107376  2.60662643]
 [-4.99        0.74348093  2.60898352]
 [-4.98        0.71592108  2.61106041]
 ...
 [ 4.98        0.09766761 -0.35620689]
 [ 4.99        0.10102249 -0.3545027 ]
 [ 5.          0.10435349 -0.35276853]]


##### Read separated lines as strings

In [27]:
fileH = open("./data/data-3-col.dat", 'r')

# read all lines, each line is a string
lines_str = fileH.readlines() 

# line_str: each string line
# number_str: each string number in line_str
numbers1 = np.array([[float(number_str) for number_str in line_str.split()] for line_str in lines_str])
numbers2 = numbers1.transpose()

print(numbers1)
print(numbers2)

fileH.close( )

##### Using with to open and process file

In [28]:
with open("./data/data-3-col.dat", 'r') as file:
    # no need to read all lines first
    numbers1 = np.array([[float(number_str) for number_str in line_str.split()] for line_str in file])

numbers2 = numbers1.transpose()

print(numbers1)
print(numbers2)

# no need to close the file

[[-5.          0.77107376  2.60662643]
 [-4.99        0.74348093  2.60898352]
 [-4.98        0.71592108  2.61106041]
 ...
 [ 4.98        0.09766761 -0.35620689]
 [ 4.99        0.10102249 -0.3545027 ]
 [ 5.          0.10435349 -0.35276853]]
[[-5.         -4.99       -4.98       ...  4.98        4.99
   5.        ]
 [ 0.77107376  0.74348093  0.71592108 ...  0.09766761  0.10102249
   0.10435349]
 [ 2.60662643  2.60898352  2.61106041 ... -0.35620689 -0.3545027
  -0.35276853]]


### Save numerical table to a file

In [33]:
# import numpy as np
fileH = open("./data/data3C-output.dat", 'w')

# numbers1 = ...

for row in numbers1:
    for column in row:
        fileH.write('%14.8f' % column)
    fileH.write('\n')

fileH.close()

In [37]:
numbers2

array([[-5.        , -4.99      , -4.98      , ...,  4.98      ,
         4.99      ,  5.        ],
       [ 0.77107376,  0.74348093,  0.71592108, ...,  0.09766761,
         0.10102249,  0.10435349],
       [ 2.60662643,  2.60898352,  2.61106041, ..., -0.35620689,
        -0.3545027 , -0.35276853]])

In [38]:
# import numpy as np
fileH = open("./data/data3C-output2.dat", 'w')

# numbers1 = ...

for row in numbers1.T:
    for column in row:
        fileH.write('%14.8f' % column)
    fileH.write('\n')

fileH.close()

### Numpy: loadtxt and savetxt

In [1]:
import numpy as np

##### Read numerical table

In [7]:
a = np.loadtxt('./data/data-3-col.dat')
print(a)
a[20, 0]

[[-5.          0.77107376  2.60662643]
 [-4.99        0.74348093  2.60898352]
 [-4.98        0.71592108  2.61106041]
 ...
 [ 4.98        0.09766761 -0.35620689]
 [ 4.99        0.10102249 -0.3545027 ]
 [ 5.          0.10435349 -0.35276853]]


-4.8

In [20]:
a = np.loadtxt('./data/data-3-col.dat', unpack = True)
print(a)
a[0, 20]

[[-5.         -4.99       -4.98       ...  4.98        4.99
   5.        ]
 [ 0.77107376  0.74348093  0.71592108 ...  0.09766761  0.10102249
   0.10435349]
 [ 2.60662643  2.60898352  2.61106041 ... -0.35620689 -0.3545027
  -0.35276853]]


-4.8

In [10]:
x, y, z = np.loadtxt('./data/data-3-col.dat', unpack=True, delimiter='\t')
print(x, y, z, sep='\n')
x[20]

[-5.   -4.99 -4.98 ...  4.98  4.99  5.  ]
[0.77107376 0.74348093 0.71592108 ... 0.09766761 0.10102249 0.10435349]
[ 2.60662643  2.60898352  2.61106041 ... -0.35620689 -0.3545027
 -0.35276853]


-4.8

##### Save numerical table

In [16]:
numbers1 = x[19:50]
np.savetxt("./data/numbers1.dat", numbers1, fmt="%14.8f")

In [17]:
numbers2 = y[y<1]
np.savetxt("./data/numbers2.dat", numbers2, fmt="%14.8f")

In [22]:
numbers3 = a[:, 0]
np.savetxt("./data/numbers3.dat", numbers3, fmt="%14.8f")